#!/bin/bash
#
# lib/magnum
# Functions to control the configuration and operation of the **magnum** service

# Dependencies:
#
# - ``functions`` file
# - ``DEST``, ``DATA_DIR``, ``STACK_USER`` must be defined
# - ``SERVICE_{TENANT_NAME|PASSWORD}`` must be defined

# ``stack.sh`` calls the entry points in this order:
#
# - install_magnum_capi_helm

# Save trace setting
XTRACE=$(set +o | grep xtrace)
set +o xtrace

# Defaults
# --------

# Set up default directories
MAGNUM_REPO=${MAGNUM_CAPI_HELM_REPO:-${GIT_BASE}/openstack/magnum-capi-helm.git}
MAGNUM_BRANCH=${MAGNUM_CAPI_HELM_BRANCH:-master}
MAGNUM_DIR=$DEST/magnum-capi-helm

# install_magnum_capi_helm() - Collect source and prepare
function install_magnum_capi_helm {
    git_clone $MAGNUM_CAPI_HELM_REPO $MAGNUM_CAPI_HELM_DIR $MAGNUM_CAPI_HELM_BRANCH
    setup_develop $MAGNUM_CAPI_HELM_DIR
}

