- hosts: all
  tasks:
    - name: Set up ipv4 iptables rules for Kubernetes
      become: yes
      iptables:
        state: present
        action: insert
        chain: INPUT
        ip_version: ipv4
        source: "{{ item }}"
        jump: ACCEPT
      with_items:
        # Default pod cidr
        - "10.100.0.0/16"
        # Default kubernetes service cidr
        - "172.24.0.0/13"